[build]
  command = "./build.sh"
  functions = "./functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/lhbelfanti/views-counter/functions"
  GO111MODULE = "on"
  GOBIN = "/opt/build/repo/functions"