[build]
command = "./build.sh"
functions = "functions"
publish = "public"

[build.environment]
GO_IMPORT_PATH = "github.com/lhbelfanti/views-counter"
GO111MODULE = "on"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/views-counter/:splat"
status = 200